### ISSUE TITLE
Pass enumeration and referrer URL with "Need help?"

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#102]
The form used for the "Need help? - Ask a Librarian" link at the item level should pass item enumeration info (volume, issue, year, etc.), and pass the referring URL of the page from which the form was submitted.

**Comment by bbusenius** [comment]
If I understand this correctly, I am to create two new form fields on the "Need help? - Ask a Librarian" form.

1. Referring URL: will be a hidden field
2. An item enumeration info field: will be visible and should have volume, issue, year, etc.

I'm struggling with issue in this case. When I look at the Scan & Deliver form, I see that we have a separate field for _issue_ but I'm unable to find an example where it's actually populated. I will likely be using [this API to populate the field](http://forms2.lib.uchicago.edu/lib/searchform/itemServlet.php?format=json&bib=3018859&barcode=096353271&database=testing). Do I need anything beyond `volumeNumber` and `copyNumber` from that API?

**Comment by dbietila** [comment]
Those fields are fine. We do not need anything more.

**Comment by bbusenius** [comment]
[This is ready to go on dldc1](https://dldc1.lib.uchicago.edu/vufind/Record/2412798). Let me know if I can deploy.

**Comment by dbietila** [comment]
This looks good to me.

**Comment by bbusenius** [comment]
This is deployed.
