### ISSUE TITLE
Services - UBorrow and Borrow Direct links should appear next to items on reserve, even when available

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#12]
[Bug 15827](http://trouble.lib.uchicago.edu/bugzilla/show_bug.cgi?id=15827) - Services - UBorrow and Borrow Direct links should appear next to items on reserve, even when available

Ideally, the following 14 shelving locations would display the
UBorrow/BorrowDirect links regardless of item status:

Location Code    Location Name
ResupS    Needed for Reserve Next Quarter; Ask at SSA Circulation Desk
JRLRES    Regenstein, 1st Floor Reserve Desk
Resup    Needed for Reserve Next Quarter: Ask at Regenstein, 1st Floor
Circulation
SSAdRes    Social Service Administration, Reserve
Res    Needed for Reserve Next Quarter; Ask at Regenstein Circulation Desk
LawRes    D'Angelo Law Reserve Room
LawResC    D'Angelo Law Reserve Room
LawResP    D'Angelo Law Reserve Room
ResupD    Needed for Reserve Next Quarter; Ask at D'Angelo Law Circulation Desk
EckRes    Eckhart, Reserve
ResupE    Needed for Reserve Next Quarter; Ask at Eckhart Circulation Desk
ResupC    Needed for Reserve Next Quarter; Ask at Crerar Circulation Desk
SciRes    Crerar, 1st Floor Reserve Desk
ArtResA    Regenstein, Room 420, East Asian Art Collection

**Comment by bbusenius** [comment]
Are these all the location statuses or are there others besides these (that would only show when not available)?

**Comment by dbietila** [comment]
I believe that is everything. I think we'd want to check for that location in both copy and item levels. Often, stuff gets put in a reserve location on a temporary basis (at the item level).
