### ISSUE TITLE
remove Mansueto as a pickup location in VuFind recall form and patron profile

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#13]
[Bug 20170](http://trouble.lib.uchicago.edu/bugzilla/show_bug.cgi?id=20170) - remove Mansueto as a pickup location in VuFind recall form and patron profile

Important prereq for paging
Rewrite that to Reg for anyone who has selected it

**Comment by bbusenius** [comment]
Fixed in dev. Since this setting is in OLE.ini, it needs to be manually copied to production. If it looks good on dldc1, I'll go ahead and do that.
