### ISSUE TITLE
Call numbers are difficult to see

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#17]
Multiple testers are reporting that it is difficult to notice call numbers in their current placement. Disc Tools suggests styling call numbers to be more attention-grabbing.

**Comment by kzadrozny** [comment]
I'll edit the LESS file directly for these small changes and will have @bbusenius upload the changes.

**Comment by kzadrozny** [comment]
@bbusenius This new LESS file is ready for your action.

**Comment by bbusenius** [comment]
I had to manually add the file to avoid a merge conflict.

**Comment by dbietila** [comment]
Looks good. Let's try this.
