### ISSUE TITLE
Extent of ownership columns should be wider if not all elements are present

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#19]
Extent of Ownership can have columns for Issues, Supplements, and Indexes. If one or more of those columns is not present on a record, other column should extend to fill the width of the display area.

**Comment by kzadrozny** [comment]
Ownership types means type or holding object, such as Issues, supplements, or indexes.

If ownership types ==3

```
<div class="col-sm-4"> ... </div>
<div class="col-sm-4"> ... </div>
<div class="col-sm-4"> ... </div>
```

If ownership types < 3

```
<div class="col-sm-6"> ... </div>
<div class="col-sm-6"> ... </div>
```

If only 1 ownership type, place data in first div. Empty second col-sm-6 div is OK.

**Comment by dbietila** [comment]
This is better.
