### ISSUE TITLE
Subject browse timeouts

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#2]
[Bugzilla 19967](http://trouble.lib.uchicago.edu/bugzilla/show_bug.cgi?id=19967)

**Comment by todolson** [comment]
This is properly part of the vufind-browse-handler code. Here's the pull request where we're discussing and tracking: https://github.com/vufind-org/vufind-browse-handler/pull/23

**Comment by todolson** [comment]
I tried the browse searches in the Bugzilla ticket. Responses are snappy, even for entries with thousands of records. Clearly the code changes that we merged some time ago have been deployed in our local production.
