### ISSUE TITLE
Trim item records to display over two rows, not three

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#22]
See KZ's mockups for reference: https://kzadrozny.github.io/VuFind/record-serial.html

**Comment by bbusenius** [comment]
It looks like this needs to be handled in the LESS/CSS. I'm going to reassign to KZ for the moment.

**Comment by kzadrozny** [comment]
@bbusenius Some mark-up needs to change for this to get fixed

The two items in that td are currently:
```
<span>Loan period: 7 day loan, no renewals&nbsp;</span>
<span class="text-success">Available<link property="availability" href="http://schema.org/InStock"></span>
```

But they need to change to:
```
<span class="text-success">
   Available<link property="availability" href="http://schema.org/InStock">
    <span class="loan-period">
       Loan period: 7 days, non-renewable
    </span>
</span>
```

Basically, the loan period span gets a class and goes inside the text-success span, at the end.

**Comment by dbietila** [comment]
This looks better. We may want to consider further iterations, but it is definitely an improvement.
