### ISSUE TITLE
Display public item notes

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#27]
I realized our spec included displaying public item notes again. Here are some example records with notes:

https://catalog.lib.uchicago.edu/vufind/Record/22031
https://catalog.lib.uchicago.edu/vufind/Record/2330472 
https://catalog.lib.uchicago.edu/vufind/Record/2349369

**Comment by dbietila** [comment]
Kathy, I remember I sent you examples of item note records a while back, but I can't remember if this ever made it onto a mock. If a mock with item notes exists, can you share with Brad?

**Comment by kzadrozny** [comment]
I thought I had a mock showing item notes on a physical copy, but all I could find is an item note attached to an online item here: https://kzadrozny.github.io/VuFind/record-monograph.html

@bbusenius The styling and location is the same for a physical copy item note as you see in the mock above.

**Comment by dbietila** [comment]
Examples look good to me.
