### ISSUE TITLE
Call numbers sometimes truncated unexpectedly in "Consult the series record" links

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#29]
Links are being built with a partial call number in these cases, resulting in an incorrect browse. This always existed in VuFind, but is aggravated now that we link directly to full records in these cases.

https://catalog-test.lib.uchicago.edu/vufind/Record/5721243
https://catalog-test.lib.uchicago.edu/vufind/Record/5718953

**Comment by bbusenius** [comment]
Call number examples:
http://ole01.uchicago.edu:8180/solr/bib/select?q=DocType%3Aitem%2C+ItemBarcode_display%3AA*&rows=1000&fl=bibIdentifier%2C++HoldingsCallNumber_display&wt=csv&indent=true
