### ISSUE TITLE
Barcode indexing

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#3]
- [ ] Add item barcode to export from OLE 
- [ ] Add mult-valued barcode field to Solr (string field)

**Comment by seanfilipov** [comment]
David,
 Give me more information please. What field number(example: 245a, 740b or 800d) should it be?

**Comment by todolson** [comment]
Sean, the barcode is part of the item data, so it should be go into the same field as the other item data. You can look at the export profile to be certain. It will need its own subfield. 

Remember to add it to all of the VuFind export profiles.

**Comment by seanfilipov** [comment]
Barcode information was added to 097b field.
Files updated: schema.xml in biblio core and marc.properties

The change is in catalogtest only right now.
OLE export profiles are updated.

**Comment by dbietila** [comment]
I am testing with item barcode 14057857, and getting not results on catalogtest.

Please compare the parent bib record on production and catalog test: 
https://catalog.lib.uchicago.edu/vufind/Record/557518
https://catalogtest.lib.uchicago.edu/vufind/Record/557518

I notice that no holdings are indexed on the catalogtest version. Are we missing a lot of holdings and items in the catalogtest index? Should I just ignore this case?

**Comment by dbietila** [comment]
Also compare:
https://catalog.lib.uchicago.edu/vufind/Record/222910
https://catalogtest.lib.uchicago.edu/vufind/Record/222910

Again, there are no holdings displayed in catalogtest.

**Comment by dbietila** [comment]
https://catalogtest.lib.uchicago.edu/vufind/Record/4787933
https://catalog.lib.uchicago.edu/vufind/Record/4787933

**Comment by todolson** [comment]
No holdings are displaying because there is a problem with `oletest` right now. A scheduled data update failed last night. OLE on oletest is unavailable while Dale investigates.

The `OLE.ini` file could be changed to temporarily point to a different OLE server.

**Comment by dbietila** [comment]
The index is behaving well for me. I am going to ask Access Services (the requester) to test it, and will pass on any comments.

**Comment by dbietila** [comment]
No problems found. Can you put this into production VuFind?

**Comment by seanfilipov** [comment]
The code is in catalog production now.
