### ISSUE TITLE
Online holdings without call numbers blue

### ISSUE THREAD

**Issue by ecboettch** [uchicago-library/vufind#33]
Example (online holdings with print holdings): https://catalog.lib.uchicago.edu/vufind/Record/101508

Example (online holdings w/o print holdings - I was wrong in standup, this is an issue as well): https://catalog.lib.uchicago.edu/vufind/Record/ocm01586310

Example with correct styling: https://catalog.lib.uchicago.edu/vufind/Record/2386211

**Comment by kzadrozny** [comment]
@bbusenius The issue is data being put all in one div, rather than two separate divs. The second div, where the links are housed, is missing.
 
**Structure should be:**

```
<div class="holdings-locpanel">
  <div class="locpanel-heading online">  ["Online" and call number]  </div>
  <div id="e-links" class="holdings-unit">  [links to journal sources]  </div>
</div>
```

**Structure currently is:**

```
<div class="holdings-locpanel">
  <div class="locpanel-heading online">  ["Online", call number, links to journal sources]  </div>
</div>
```
