### ISSUE TITLE
On Order or In Process statuses should have a request link

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#36]
http://trouble.lib.uchicago.edu/bugzilla/show_bug.cgi?id=17702

I'm told that OLE will now allows requests to be initiated for items without a barcode, so we can enable a request for items with the On Order and In Process statuses.

There was interest in assigning a label other than Recall This. Suggestions included "Place a Hold" and "Notify upon Receipt". There was a suggestion that Emma could look at labeling.

**Comment by bbusenius** [comment]
This is setup and working on https://dldc1.lib.uchicago.edu/vufind/. All we need now is the language for the link.
