### ISSUE TITLE
"Shelved In" Different Location Fix

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/vufind#37]
Improve visibility of "Shelved In" item level note

![screen shot 2017-10-05 at 10 31 09 am](https://user-images.githubusercontent.com/10147408/31235953-5ca20664-a9b8-11e7-9dcc-9ebf0a03be57.png)

## Mark-up Changes
- Remove `<br>` before `<span class="holding-location">`

- Replace icon of `<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>` with `<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>`

- Add following code inside  `locpanel-heading` div between `</h2><br>` and `<h3>`:
```
<span class="location-change">Some volumes on Reserve at {{ LOCATIONS }}</span>
```
Full code for above should look like:
```
<div class="locpanel-heading">
<h2>Regenstein, Bookstacks</h2>
<a href="http://forms2.lib.uchicago.edu/lib/maplookup/maplookup.php?bib=83880&amp;barcode=46321731" class="service external" target="_blank"><i class="fa fa-map-marker" aria-hidden="true"></i> Map/guide</a>
<br>
<span class="location-change">Some volumes on Reserve at Regenstein, 1st Floor Reserve Desk              </span>
<h3><span>Call Number: </span> D57.C24 c.3</h3><a href="/vufind/alphabrowse/Home?source=lcc&amp;from=D57.C24" class="ablink">(Browse by Call Number)</a>
<br>
</div>
```

## Style changes
ADD:
```
.locpanel-heading .location-change {
    margin-top: -5px;
    font-weight: 600;
}
```

**Comment by kzadrozny** [comment]
Mock up for testing: https://kzadrozny.github.io/VuFind/record-Cambridge.html

**Comment by ecboettch** [comment]
Update from testing last Friday - while the changes to the item-level note styling are partly (not totally) effective, the note near call # led a couple participants to conclude that all the items were on reserve. 
full report: https://loop.lib.uchicago.edu/documents/1263/report_sa.pdf

**Comment by kzadrozny** [comment]
Per user testing, new mock will:
- include "alert" icon in the header of the holding's box
- use more general language for the first alert

**Comment by kzadrozny** [comment]
New mock for @ecboettch and @dbietila to review: https://kzadrozny.github.io/VuFind/record-Cambridge2.html

**Comment by kzadrozny** [comment]
@dbietila Has this been pushed to production/can this issue be closed?
