### ISSUE TITLE
Linking to results from a title browse sometimes fails

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#42]
In some cases, on Title Browse results pages, clicking a result is producing incorrect results. The problem cases:

- have a Count or 5 or more
-have a difference in punctuation with a Uniform Title listed in the records

Ex.:  https://catalog.lib.uchicago.edu/vufind/Alphabrowse/Home?source=title&from=Carmen.%20French&page=-1

Click on the Result for "Carmen English", which lists a result Count of 7.
https://catalog.lib.uchicago.edu/vufind/Search/Results?type=TitleBrowse&lookfor=%22Carmen%20English%22

There are no results.

If we instead linked to "Carmen. English", we would get better results.
https://catalog.lib.uchicago.edu/vufind/Search/Results?lookfor=%22Carmen.+English%22&type=AllFields&limit=60&sort=relevance

I suspect that we are stripping (some) punctuation from Uniform Titles when they are indexed in the Title (and All Fields) indexes. This causes searches for those Uniform Titles to fail.

I'm not sure if it would be best to:

- Change how we index Uniform Titles
-Change how we construct search URLs for these records from the Browse results page

But we need to do something to ensure that we are not erroneous giving users "No Result" pages when they click on a Browse entry.

**Comment by todolson** [comment]
@seanfilipov : Check the Solr document for some of these records. Is the punctuation being stripped when we add the uniform title (240) to `title_browse` or `title_browse_sort`? Is there something else that's funny about the data?

**Comment by dbietila** [comment]
There is definitely some improvement, but I am still findings cases that fail. On the same browse page: 
https://catalogtest.lib.uchicago.edu/vufind/Alphabrowse/Home?from=carmen.+english&source=title

Try clicking some of the titles with semicolons in them:
Carmen fantasy; arr.
Carmen fantasy; arranged.

Those links are still failing to produce results. Please let me know if you need me to find more cases.

**Comment by todolson** [comment]
@seanfilipov, here is the title browse URL for "Carmen fantasy; arr.":
https://catalogtest.lib.uchicago.edu/vufind/Search/Results?type=TitleBrowse&lookfor=%22Carmen%20fantaisie%3B%20arr.%22

Since this gives no result, you need to check the browse handler directly. Do this browse through the browse handler directly. See what the results are, and also monitor the Solr logs for any errors. There may be a stack trace.

The questions to ask about the search failure are:
1. What error is being reported in the logs?
2. Which field does the search term come from?
3. Which field is the browse handler searching? (You may need to read the Solr config.)

I will plan to come into the office after my classes, by 4pm.

**Comment by todolson** [comment]
Here's the problem: when a title browse entry has more than 5 hits, the search term for the link has come from the `title_browse` field, but the link searches Solr using the `title_full` field. So there is a mismatch.

I believe this will need to be addressed in the front end.

Here's a sample search into the title browse, fill in the host and port as appropriate:
http://[HOST]:[PORT]/solr/biblio/browse?json.nl=arrarr&offset=0&extras=author:format:publishDate&from=carmen.+english&source=title&rows=60&wt=json

Here is a sample row from the result, stripped down:
```
{
  "note": "",
  "heading": "Carmen. Chanson du toréador.",
  "useInstead": [],
  "count": 25,
  "ids": [...],
  "extras": {
    "author": [...],
    "format": [...],
    "publishDate": [...]
  },
  "sort_key": "Carmen. Chanson du toréador",
  "seeAlso": []
}
```

In the JSON result for a title browse, the `heading` corresponds to the Solr `title_browse` field, and `sort_key` corresponds to `title_browse_sort`. You could construct the link from the `heading` value and search the Solr `title_browse` field, or construct the link from the `sort_key` and search the Solr `title_browse_sort`. I'm not certain if there's a reason to prefer one over the other. `heading` will be an exact string, `sort_key` is normalized for sorting.

**Comment by todolson** [comment]
@bbusenius, you are now on this ticket. I think you will have to do the next layer of investigation.

**Comment by bbusenius** [comment]
The links in the template aren't so straightforward. The templates just display what they're given and don't have access to those fields. I did some poking around and found an entry in searchspecs.yaml that seems related. 

``TitleBrowse:
  QueryFields:
    title_full:
      - [onephrase, ~]

When I change title_full to title_browse in that entry, it seems to solve the problem. Is that an acceptable solution?

**Comment by todolson** [comment]
That is the perfect solution! We should have thought of that.

**Comment by bbusenius** [comment]
Great! I deployed this on test: https://catalog-test.lib.uchicago.edu/vufind/Alphabrowse/Home?from=Carmen.+French&source=title. If you give me the thumbs up, I'll push it to production.

**Comment by todolson** [comment]
Looks good to me. Once you push to prod, please close this ticket.
