### ISSUE TITLE
Can "Stored offsite" status be orange?

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#49]
We now have some SPR records in VuFind.

https://catalog.lib.uchicago.edu/vufind/Record/236463
https://catalog.lib.uchicago.edu/vufind/Record/83460
https://catalog.lib.uchicago.edu/vufind/Record/2377697
https://catalog.lib.uchicago.edu/vufind/Record/2328197

Can the "Stored offsite" status be made to display in orange, as per the mock at https://kzadrozny.github.io/VuFind/record-Social-Work.html

**Comment by kzadrozny** [comment]
This is a mark-up issue. @johnjung - can you change

````
<span class="text-danger">Stored offsite<link property="availability" href="http://schema.org/OutOfStock"></span>
```

to 

```
<span class="text-unknown">Stored offsite<link property="availability" href="http://schema.org/InStock"></span>
```

Additionally, the ILL button is not being populated in `<span class="service-links">`

**Comment by dbietila** [comment]
ILL button is a separate ticket.

https://github.com/uchicago-library/vufind/issues/48

**Comment by bbusenius** [comment]
This is done.
