### ISSUE TITLE
Index and display 930 in Series indexes

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#71]
Technical services is planning to move the contents of the 830 field to the 930 field. We should plan to update indexes accordingly.

1) For 'series2' and 'series_browse' 

ADD
930adfghklmnoprst
LNK930adfghklmnoprst

2) For 'allfields' and 'allfields_unstemmed' 

Change from
"All searchable fields between 100 and 900"
to
"All searchable fields between 100 and 900, 930"

Example records with a 930 fields are:
3369224
7542178
4713918
1202186
7486404

**Comment by dbietila** [comment]
Sean reports that these changes have been made, but are currently only showing up on vfweb05.

Next, Brad will next to add the 930|adfghklmnoprstv to the Series Stanza on the full record display.

**Comment by bbusenius** [comment]
The full record display has been updated to show `930|adfghklmnoprstv` fields. Do we also need to update the results view display? We currently show `830|anpvsx` fields on the results page.
