### ISSUE TITLE
Need "Video Game Collection" item_collection defined in VuFind.

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#76]
We need to add a new item collection for the OLE location UC/JCL/Games with a name of "Video Game Collection".

It should display in the Advanced Search page as a Collection under the Crerar Library location.

**Comment by bbusenius** [comment]
I think this might also need to be added to the service link configuration. Any idea how that should be modeled?

**Comment by seanfilipov** [comment]
Changes done on pyrite. Waiting for Brad to do his part.

**Comment by bbusenius** [comment]
When I do a search and filter on Pyrite for something with an `item_collection` of `Video+Game+Collection`, I don't get any results. 

https://pyrite.lib.uchicago.edu/vufind/Search/Results?sort=relevance&join=AND&bool0[]=AND&lookfor0[]=&type0[]=AllFields&lookfor0[]=&type0[]=AllFields&lookfor0[]=&type0[]=AllFields&filter[]=item_collection%3A%22Video+Game+Collection%22&daterange[]=publishDate&publishDatefrom=&publishDateto=

Also, when I query pyrite solr directly for `item_collection:*`, I don't get any results.

http://pyrite.lib.uchicago.edu:8080/solr/biblio/select?q=item_collection:*

Are we missing something?
