### ISSUE TITLE
Author sort not working

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#8]
[Bugzilla 19893](http://trouble.lib.uchicago.edu/bugzilla/show_bug.cgi?id=19893)

**Comment by seanfilipov** [comment]
In  local/import/marc.properties  added two fields:

author_sort = 100abcdjq:110abcdgn:111acdegnq, clean
<field name="author_sort" type="string" indexed="true" stored="false"/>

Commit: 6d51de289
