### ISSUE TITLE
Advanced search Boolean logic for multiple Location/Collection limits

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#81]
If one limits to multiple collections on the Advanced Search page, the limits are currently are getting ANDed together, which is unproductive for most searches. If multiple Locations are applied as post-search facets, they get ORed together.

Can we switch the behavior on Advanced Search so that if Multiple Locations and/or Collections are selected, they are ORed together?

Example search URL:
https://catalog.lib.uchicago.edu/vufind/Search/Results?sort=relevance&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&filter%5B%5D=building%3A%22Special+Collections+Research+Center%22&filter%5B%5D=item_collection%3A%22American+Drama%22&filter%5B%5D=item_collection%3A%22Atkinson+Collection+of+American+Drama%22&filter%5B%5D=item_collection%3A%22Austrian+Collection+of+Drama%22&filter%5B%5D=item_collection%3A%22Drama+Collection%22&daterange%5B%5D=publishDate&publishDatefrom=1800&publishDateto=1900

**Comment by bbusenius** [comment]
I think I have this setup the way we want. You can test it on dldc1: https://dldc1.lib.uchicago.edu/vufind/Search/Advanced
