### ISSUE TITLE
Enable display of Syndetics first chapters in VuFind

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#91]
We subscribe to a first chapter service through Syndetics, and need to enable display of this content in VuFind.

It looks as though there may be VuFind code to enable this in the Excerpts tab. https://vufind.org/jenkins/job/VuFind/javadoc/classes/VuFind.Content.Excerpts.Syndetics.html

**Comment by bbusenius** [comment]
Can I get some example bibs where I should expect to see these?

**Comment by dbietila** [comment]
Jessica has asked for a list of ISBNs for which they have coverage. We're waiting for them to provide that.

**Comment by dbietila** [comment]
Here's the syntax for grabbing a first chapter by ISBN:

http://syndetics.com/index.php?isbn=9780060731328/dbchapter.html&client=chicagoh&type=#dbchapter

or

http://syndetics.com/index.php?isbn=9780060731328/dbchapter.xml&client=chicagoh

**Comment by dbietila** [comment]
Some documentation is here: https://developers.exlibrisgroup.com/wp-content/uploads/2010/05/SyndeticsStarterDocument.pdf

**Comment by dbietila** [comment]
Actually, this record in VF https://catalog.lib.uchicago.edu/vufind/Record/4892474 seems to have an ISBN for which there is an excerpt available.

http://syndetics.com/index.php?isbn=0385509456/dbchapter.html&client=chicagoh&type=

**Comment by bbusenius** [comment]
Thanks!

**Comment by bbusenius** [comment]
[This is now enabled on dldc1](https://dldc1.lib.uchicago.edu/vufind/Record/4892474/)

**Comment by dbietila** [comment]
Disc Tools decided that they did want to try putting this in production. We will also need a Google Analytics event for users clicking on the "Excerpts" tab in VuFind.

**Comment by bbusenius** [comment]
This is done and deployed. It looks like jej wrote the Google Analytics bit to track any and all tabs, so the new tab is added automatically. Thanks to him we get that bit for free.

**Comment by dbietila** [comment]
Thanks, past John!
