### ISSUE TITLE
Add Shib IDP parameter to Hathi emergency access links

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#95]
Cornell is including a parameter in their Hathi emergency access links that prompts a SSO login when visiting a record. 

Eg: https://catalog.hathitrust.org/Record/002708281?signon=swle:https://shibidp.cit.cornell.edu/idp/shibboleth

We should create our links with this parameter, pointing to the UChicago Shibboleth IDP.

**Comment by dbietila** [comment]
I'm not sure what the exact syntax ought to be, but documentation is here: https://uchicago.service-now.com/it/itservices@uchicago.edu?id=kb_article&sys_id=27420876139ec41cf44779566144b059

**Comment by dbietila** [comment]
Syntax of:

https://catalog.hathitrust.org/Record/002708281?signon=swle:urn:mace:incommon:uchicago.edu

seems to be productive.

**Comment by dbietila** [comment]
https://babel.hathitrust.org/cgi/pt?id=uc1.b4928509&signon=swle:urn:mace:incommon:uchicago.edu also works for me, and is closer to our current syntax

**Comment by bbusenius** [comment]
I think this [is working as intended on dlc1](https://dldc1.lib.uchicago.edu/vufind/Record/1000000). You'll want to check normal Hathi records in addition to ETAS records to be sure they're working correctly as well. I believe they are but want to be sure.

Do we want to turn off the "Login Directions" helper link as well?
